baseURL = 'https://triankl3.github.io/'
languageCode = 'en-us'
title = 'triankl3'
copyright = 'WRITE COPYRIGHT HERE'
disableKinds = ["RSS"]

[module]
    [[module.mounts]]
    source = "assets"
    target = "assets"

    [[module.mounts]]
    source = "node_modules/modern-normalize/modern-normalize.css"
    target = "assets/css/modern-normalize.css"

    [[module.mounts]]
    source = "node_modules/masonry-layout/dist/masonry.pkgd.min.js"
    target = "assets/js/masonry.pkgd.min.js"

[imaging]
    bfColor = "#ffffff"
    hint = 'photo'
    quality = 75
    resampleFilter = "lanczos"