baseURL = 'https://triankl3.github.io/'
languageCode = 'en-us'
title = 'triankl3'
copyright = 'WRITE COPYRIGHT HERE'
disableKinds = ["RSS"]
enableRobotsTXT = true
enableEmoji = true

[params]
    [params.contact]
        github = 'https://github.com/triankl3'
        twitter = 'https://twitter.com/triankl3'
        linkedin = 'https://www.linkedin.com/in/triankl3/'
        discord = '@triankl3'
        email = 'triankl3@gmail.com'

[permalinks]
    projects = "/:filename/"

[markup]
  [markup.tableOfContents]
    pre = ""
    post = ""

[module]
    [[module.mounts]]
    source = "assets"
    target = "assets"

    [[module.mounts]]
    source = "static"
    target = "static"

    [[module.mounts]]
    source = "node_modules/modern-normalize/modern-normalize.css"
    target = "assets/css/modern-normalize.css"

    [[module.mounts]]
    source = "node_modules/masonry-layout/dist/masonry.pkgd.min.js"
    target = "assets/js/masonry.js"

    [[module.mounts]]
    source = "node_modules/fit-text-webcomponent/dist/index.min.js"
    target = "assets/js/fitTextWebComponent.js"

    [[module.mounts]]
    source = "node_modules/scroll-to-element/build/scrollToElement.js"
    target = "assets/js/scrollToElement.js"

    [[module.mounts]]
    source = "node_modules/vanilla-tilt/dist/vanilla-tilt.min.js"
    target = "assets/js/vanillaTilt.js"

[imaging]
    bgColor = "#111111"
    hint = 'photo'
    quality = 95
    resampleFilter = "Lanczos"