baseURL = 'https://triankl3.github.io/'
languageCode = 'en-us'
title = 'triankl3'
copyright = 'WRITE COPYRIGHT HERE'
disableKinds = ["RSS"]

[params]
    [params.contact]
        github = 'https://github.com/triankl3'
        twitter = 'https://twitter.com/triankl3'
        linkedin = 'https://www.linkedin.com/in/triankl3/'
        discord = '@triankl3'
        email = 'triankl3@gmail.com'

[permalinks]
    projects = "/:filename/"

[module]
    [[module.mounts]]
    source = "assets"
    target = "assets"

    [[module.mounts]]
    source = "static"
    target = "static"

    [[module.mounts]]
    source = "node_modules/modern-normalize/modern-normalize.css"
    target = "assets/css/modern-normalize.css"

    [[module.mounts]]
    source = "node_modules/masonry-layout/dist/masonry.pkgd.min.js"
    target = "static/js/masonry.pkgd.min.js"

    [[module.mounts]]
    source = "node_modules/fitty/dist/fitty.min.js"
    target = "static/js/fitty.min.js"

[imaging]
    bgColor = "#111111"
    hint = 'photo'
    quality = 95
    resampleFilter = "Lanczos"