baseURL = 'https://triankl3.com/'
languageCode = 'en-us'
title = 'triankl3'
copyright = 'Design and content subject to copyright triankl3.com(Nikola Pešević).'
disableKinds = ["RSS"]
enableRobotsTXT = true
enableEmoji = true

[params]
    description = 'Personal blog and portfolio in one. Showcasing projects and celebrating the process alongside the solution.'
    source = 'https://github.com/triankl3/triankl3.github.io'
    [params.contact]
        github = 'https://github.com/triankl3'
        twitter = 'https://twitter.com/triankl3'
        linkedin = 'https://www.linkedin.com/in/triankl3/'
        discord = '@triankl3'
        email = 'triankl3@gmail.com'

[permalinks]
    projects = "/:filename/"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    pre = ""
    post = ""
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    style = 'github-dark'

[module]
    [[module.mounts]]
    source = "assets"
    target = "assets"

    [[module.mounts]]
    source = "static"
    target = "static"

    [[module.mounts]]
    source = "node_modules/modern-normalize/modern-normalize.css"
    target = "assets/css/modern-normalize.css"

    [[module.mounts]]
    source = "node_modules/masonry-layout/dist/masonry.pkgd.min.js"
    target = "assets/js/masonry.js"

    [[module.mounts]]
    source = "node_modules/fit-text-webcomponent/dist/index.min.js"
    target = "assets/js/fitTextWebComponent.js"

    [[module.mounts]]
    source = "node_modules/scroll-to-element/build/scrollToElement.js"
    target = "assets/js/scrollToElement.js"

    [[module.mounts]]
    source = "node_modules/vanilla-tilt/dist/vanilla-tilt.min.js"
    target = "assets/js/vanillaTilt.js"

    [[module.mounts]]
    source = "node_modules/motion/dist/motion.min.js"
    target = "assets/js/motion.js"

    [[module.mounts]]
    source = "node_modules/photoswipe/dist/umd/photoswipe.umd.min.js"
    target = "assets/js/photoswipe.js"

    [[module.mounts]]
    source = "node_modules/photoswipe/dist/umd/photoswipe-lightbox.umd.min.js"
    target = "assets/js/photoswipe-lightbox.js"

    [[module.mounts]]
    source = "node_modules/photoswipe/dist/photoswipe.css"
    target = "assets/css/photoswipe.css"


[imaging]
    bgColor = "#111111"
    hint = 'photo'
    quality = 95
    resampleFilter = "Lanczos"